name: LineageOS CI

on:
  workflow_dispatch:

jobs:
  build:
    name: LineageOS Build CI
    runs-on: ubuntu-18.04

    steps:
      - name: Maximizing build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'

      - name: Installing build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install zip gcc-multilib g++-multilib \
            libc6-dev-i386 lib32ncurses5-dev lib32z1-dev \
            libgl1-mesa-dev libxml2-utils xsltproc schedtool
          sudo ln -f -s /usr/bin/python2.7 /usr/bin/python

      - name: Syncing LineageOS sources
        run: |
          mkdir ~/lineage
          cd ~/lineage

          mkdir ~/.bin
          sudo curl http://commondatastorage.googleapis.com/git-repo-downloads/repo | sudo tee /usr/bin/repo > /dev/zero
          sudo chmod 777 /usr/bin/repo
          repo init --depth=1 -u https://github.com/LineageOS/android.git -b lineage-15.1
          git clone --branch lineage-15.1 --single-branch --depth=1 https://github.com/viam1-dev/local_manifests.git .repo/local_manifests
          repo sync -c --force-sync --optimized-fetch --no-tags --no-clone-bundle --prune -j$(nproc --all)
          rm -rf .repo

      - name: Building LineageOS
        run: |
          cd ~/lineage
          source build/envsetup.sh
          export ALLOW_MISSING_DEPENDENCIES=true
          export LC_ALL=C
          lunch lineage_viam1-user
          make -j$(nproc --all)

      - name: Uploading LineageOS build
        uses: actions/upload-artifact@v2
        with:
          name: lineage
          path: /home/runner/lineage/out/target/product/viam1/lineage*.zip
      
      - name: Uploading LineageOS Recovery
        uses: actions/upload-artifact@v2
        with:
          name: recovery
          path: /home/runner/lineage/out/target/product/viam1/recovery.img
